Parameters: 
  MessageSNSTopicName: 
    Type: String
    Default: message
Resources:
  MessageSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Ref MessageSNSTopicName
      TopicName: !Ref MessageSNSTopicName
      Subscription:
        - Endpoint: !GetAtt MessageSQSQueue.Arn
          Protocol: 'sqs'
  MessageSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 'message'
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MessageDeadletterSQSQueue.Arn
        maxReceiveCount: 3
  MessageDeadletterSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 'message-deadletter'
